<?php 
session_start();
    include('inc/functions.php');
    $postObj = new Story(); 
   
?><!DOCTYPE html>
<html class="no-js" lang="en">
<head>
  <!-- Meta Tags -->
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="author" content="WahStory">
  <!-- Favicon Icon -->
  <link rel="icon" href="/assets/img/favicon.png">
  <!-- Site Title -->
  <title>WahStory | Terms & Conditions</title>
  <link rel="stylesheet" href="/assets/css/plugins/bootstrap.min.css">
  <link rel="stylesheet" href="/assets/css/plugins/lightgallery.min.css">
  <link rel="stylesheet" href="/assets/css/plugins/slick.css">
  <link rel="stylesheet" href="/assets/css/plugins/lightgallery.min.css">
  <link rel="stylesheet" href="/assets/css/plugins/animate.css"> 
  
  <link rel="stylesheet" href="/assets/css/style.css">
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
 
 <style>
     ol li{
         padding-top: 10px;
        padding-bottom: 10px;
     }
     li h3{
         font-size: 24px;
        font-weight: 500;
        color: #d3d1d1;
        margin-top: 20px;
        margin-bottom: 10px;
     }
     li h5 {
        font-size: 18px;
        font-weight: 500;
        color: #d3d1d1;
        margin-top: 20px;
        margin-bottom: 10px;
    }
 </style>
 
 <?php include('header.php');?>
 <!-- Start Hero -->
  <div class="cs-page_heading cs-style1 cs-center text-center cs-bg" data-src="assets/images/page-title-bg.jpeg">
    <div class="container">
      <div class="cs-page_heading_in">
        <h1 class="cs-page_title cs-font_50 cs-white_color">Terms & Conditions</h1> 
        <ol class="breadcrumb text-uppercase">
            <li class="breadcrumb-item">
              <a href="/">Home</a>
            </li>
            <li class="breadcrumb-item active">Terms & Conditions</li>
          </ol>
      </div>
    </div>
  </div>
  
   <!-- End Hero -->
  <div class="cs-height_50 cs-height_lg_40"></div>
  
   <div class="container">
    <div class="row">
        
        <div class="col-md-12">
                        <h2>Terms & Conditions</h2>
                        <h5>Last Updated: 30/9/2024</h5>
                        <p>These terms of use (“Terms”) mandate the terms on which the users (“You” or “Your” or
                            “User”) access and register on the web based platform  www.wahstory.com  The Company
                            has granted a worldwide, non-exclusive,  non-sublicensable, non-transferable and non-assignable
                            license   to   the   subsidiary   to   access,   use,  manage  and  operate  the  Platform  and  use  the
                            Company’s intellectual property in relation to its use on the Platform.</p>
                        <p>This Terms is an electronic record in terms of the Information Technology Act, 2000 and rules
                            made thereunder as applicable. The Terms is (i) published in accordance with the provisions
                            of Rule 3(1)(a) of the Information Technology (Intermediary Guidelines and Digital Media
                            Ethics Code) Rules, 2021 and (ii) generated by a computer system and does not require any
                            physical, electronic, or digital signatures by the Company.</p>
                        <p>These Terms apply to all Users of the Platform, including those Users who view and access the
                            Content, those Users who are contributors of the Materials and User which may enter into an
                            agreement  such  as,  a  sponsorship  agreement  with  the  Company.  By  clicking  on  the  “I
                            accept”  button provided in the Platform, You expressly accept these Terms and agree to be
                            legally bound by them.</p>
                        <p>The Terms are between You and the Company and the User understands and accepts that
                            Company maintains the Platform to provide Users with information about Company and its
                            Services. You also accept that You are required to read the below mentioned Terms, and any
                            use of the Platform constitutes  Your acceptance and agreement to be bound by such terms, and
                            the changes made to this Terms from time to time, relating to Your usage of the Platform as
                            communicated and made available on the Platform. If You do not agree to any of the terms
                            enumerated in the Terms and the Privacy Policy, please do not use the Platform.</p>
                        <ol>
                            <div class='container'>
                            <li class="heading">
                                <h3>DEFINITIONS  AND  INTERPRETATION</h3>
                                <p>Unless the  context otherwise  requires, for these  Terms, the  following  terms  shall have
                                    the meaning ascribed to them hereunder:</p>
                                <ol>
                                    <li class="description"><b>“Applicable  Law”</b> means all laws,  ordinances, statutes, rules, orders, decrees,
                                        injunctions, licenses, permits, approvals, authorizations, consents, waivers, privileges,
                                        agreements, and regulations of any  governmental   authority/court of law having jurisdiction in India over the relevant matter including any interpretations thereof, in
                                        effect, including but not limited to, Information Technology Act, 2000 and the rules
                                        made thereunder, Digital Personal Data Protection Act, 2023</li>
                                    <li class="description"><b>“Content”</b> shall mean any content, including but not limited to, pictures, messages,
                                        videos that may be shared, uploaded and posted on the Platform by the User
                                    </li>
                                    <li class="description"><b>“Eligibility Conditions”</b> shall have the meaning as ascribed to under Clause 2.7</li>
                                    <li class="description"><b>“Company IP”</b> shall have the meaning as ascribed to under Clause 7.1</li>
                                    <li class="description"><b>“Intellectual Property Rights”</b>means all patents, designs and drawings, trademarks,
                                        service marks, logos, domain names, and utility models, copyrights, inventions, brand
                                        names, and business names, and any similar rights and the benefit (subject to the
                                        burden) of any of the foregoing (in each case whether registered or otherwise, and
                                        includes applications for the grant of any of the foregoing and the right to apply for
                                        any of the foregoing in any part of the world)</li>
                                    <li class="description"><b>“Materials”</b> includes (i) the text, software, scripts, graphics, photos, sounds, music,
                                        videos, audio-visual combinations, interactive features and other materials and (ii)
                                        comments  and  Content that You  may  contribute  in  any  manner  on  a  particular  section
                                        of Platform via features or functionalities to the Platform</li>
                                    <li class="description"><b>“Privacy Policy”</b> shall mean the Privacy Policy available on the Platform</li>
                                    <li class="description"><b>“Personal Data”</b> shall have the meaning as ascribed to under Clause 2.3</li>
                                    <li class="description"><b>"Services"</b> shall have the meaning as ascribed under Clause 3</li>
                                    <li class="description"><b>“User / Users / You”</b> shall mean and include any such User who visits the Platform
                                        or any user who wishes to avail Services through our Platform whether registered or
                                        not on the Platform and shall not include your permitted assigns, successors, heirs,
                                        and legal representatives, unless the context requires otherwise</li>
                                    <li class="description"><b>“User Account”</b> means the personal online account created by the User to gain access
                                      and use the Platform.</li>
                                </ol>
                            </li>
                            </div>
                            <div class='container'>
                            <li class="heading">
                                <h3>USER  ACCOUNT  AND  USER  OBLIGATIONS</h3>
                                <ol>
                                    <li class="description">The User may view and / or access the Services or the Platform by simply visiting the
                                        Platform  and  clicking  on  relevant  pages  that  include,  articles,  newsletters.
                                        Furthermore,   to   access   certain   other   Services,   the   User   must   first   create   a   User
                                        Account with the Platform by providing details, including Personal Data as may be
                                        required by the Company and provided for in the Privacy Policy.</li>
                                    <li class="description"><b>Confidentiality Obligation</b>: User shall  be responsible  for  maintaining  the
                                        confidentiality of the credentials of User Account, and furthermore, Company shall
                                        process  and  maintain  the  confidentiality  of  the  Personal  Data  (defined)  in
                                        accordance  with  the  Applicable  Law  and  is  dealt  in  detail  in  the  Privacy  Policy  of
                                        Company.</li>
                                    <li class="description">In consideration of Your use of the Platform, You agree: (a) that You are of legal age
                                        and have the capacity to agree to these Terms and furthermore, if You are a parent /
                                        legal guardian of a “minor” then in that event the compliance to the Applicable Law
                                        should   be   adhered   to   and   Company   reserves   the   legal   rights   to   insert   necessary
                                        protocols  /  check  mechanism  to  enforce  the  foregoing  including  but  not  limited  to
                                        the parental / legal guardian’s consent, if required under the Applicable Law and as
                                        detailed under the Privacy Policy; (b) to provide complete, accurate, current, and
                                        required  information  about  You  as  may  be  prompted  at  the  time  of  registration  on
                                        the Platform <b>("Personal Data")</b>; (c) to maintain the security of Your password and
                                        identification;   (d)  to  maintain  and  promptly  update  the  Personal  Data  and  any
                                        information You provide to Company, to keep it accurate, current and complete for
                                        providing the Services. You are not permitted to use the Platform or submit Content
                                        to the Platform if  You do not follow these Terms.  If You provide any information that
                                        is  untrue,  inaccurate, unauthorised,  not  current, or  incomplete  (or  becomes  untrue,
                                        inaccurate, not current, or incomplete), or if the Company has reasonable grounds to
                                        suspect that such information is untrue, inaccurate, not current, or incomplete, the
                                        Company has the right to refuse any and all the Services.</li>
                                    <li class="description">You   are   entirely   responsible   for   all   Content   that   You   upload,   post,   or   otherwise
                                        transmit through Your use of the Platform. You agree not to upload, post or otherwise
                                        transmit  Content  that:  (a)  is  inaccurate,  false,  harmful,  obscene,  pornographic,
                                        defamatory, paedophilic, insulting, racist, violent, offensive, harassing on the basis of
                                        gender, unlawful as per the Applicable Law, harmful to a minor, impersonates another
                                        person, invasive of another’s privacy, relating or encouraging money laundering or
                                        gambling or otherwise objectionable to Company or other Users of the Platform; (b)
                                        includes unauthorized disclosure of Personal Data; (c) violates or infringes anyone's
                                        Intellectual Property Rights; or (d) contains software viruses or any other computer
                                        code,  files  or  programs  designed  to  interrupt,  destroy  or  limit  the  functionality  of
                                        any computer software or hardware or telecommunications equipment.</li>
                                    <li class="description">You agree not to access (or attempt to access) the Platform by any means other than
                                        through the interface that is provided by the Company. You shall not use any deep-
                                        link, robot, spider or other automatic device, program, algorithm or methodology, or
                                        any similar or equivalent manual process, to access, acquire, copy or monitor any
                                        portion of the Platform or Content (as defined below), or in any way reproduce or
                                        circumvent the navigational structure or presentation of the Platform, Materials or any
                                        Content,   to   obtain   or   attempt   to   obtain   any   Materials,   documents   or   information
                                        through any means not specifically made available through the Platform.</li>
                                    <li class="description">By using the Platform, You represent and warrant that You currently meet and will
                                        continue to meet the following eligibility conditions <b>("Eligibility Conditions")</b> for as
                                        long as You use the Platform: (a) You have and will at all times comply with all
                                        Applicable Law and regulations; (b) You have the right, authority and capacity to
                                        enter into these Terms s and to abide by all provisions stipulated in these Terms.</li>
                                    <li class="description">By using the Platform, You understand and agree that Company may rely on the above
                                        Eligibility Conditions, representations and warranties as true. You understand and
                                        agree that Company may revise the Eligibility Conditions/Terms from time to time
                                        and that User will abide by such revised Eligibility Conditions/Terms or discontinue
                                        using the Platform.</li>
                                    <li class="description">You also understand and agree Company neither confirms nor denies the validity of
                                        information provided by Users and that Company does not verify that any or all of the
                                        Eligibility Conditions are met by Users.</li>

                                </ol>
                            </li>
                            </div>
                            <div class='container'>
                            <li class="heading">
                                <h3>SERVICES PROVIDED ON THE PLATFORM</h3>
                                <ol>
                                    <li class="description">You   acknowledge   that   the   Platform   allows   You   to   avail   the   following   Services
                                        including:
                                    <ul>
                                        <li class="description">The Platform provides easily accessible content, connections and communications
                                            that powers brand and business objectives generated, developed or produced by the
                                            Company or aggregated, obtained and/or licensed through third party sources / third
                                            party inputs.</li>
                                        <li class="description">Promptly and efficiently responding to Your queries or issues relating to Your User
                                            Account and the Services availed through the Platform.
                                         <p class="description">(Collectively, referred to as <b>“Services”</b>)</p>
                                        </li>
                                    </ul>
                                    </li>
                                    <li class="description">The Company may, at its discretion, add, modify, or remove any of the Services listed
                                        above from time to time. The Company may also, at its discretion, have terms and
                                        conditions specific to any category or section in addition to these Terms.</li>
                                    <li class="description">The Company does not (i) adopt any ‘unfair trade practices’ either on the Platform
                                        or  otherwise with respect to the Services; and (ii) discriminate between Users of the
                                        same class or arbitrarily classify the Users.</li>
                                </ol>
                            </li>
                            </div>
                            <div class='container'>
                            <li class="heading">
                                <h3>PROPRIETARY  RIGHTS  AND  INTELLECTUAL  PROPERTY  RIGHTS</h3>
                               <ol>
                                <li class="description">User acknowledges and agrees that this Platform and the Content posted herein, which
                                    shall include but shall not be limited to pictures, branding, text, Content, graphics,
                                    designs, brand logos, audio, video, interfaces and/or any other information, or any
                                    Intellectual Property Rights (whether those rights happen to be registered or not, and
                                    wherever   in   the   world   those   rights   may   exist)   and/or   the   overall   arrangement   of
                                    Content   is   protected   and   is   owned,   controlled   or   licensed   by   or   to   Company;   all
                                    comments, feedback, ideas, suggestions, information or any other Content provided
                                    by You (hereinafter referred to as <b>“Company IP”</b>). You may not modify, publish,
                                    copy, transmit, transfer, sell, reproduce, modify, create derivative works from, license,
                                    distribute, frame, hyperlink, download, repost, perform, translate, mirror, display or
                                    commercially   exploit   Company   IP   in   any   other   way   unless   the   User   has   agreed
                                    otherwise with Company in writing. User further acknowledges that the Services may
                                    contain  information  which  is  designated  confidential  by  Company  and  that User  shall
                                    not disclose such information without the Company's prior written consent.</li>
                                <li class="description">You agree not to use any framing techniques to enclose any trademark or logo or other
                                    Company   IP,   or   remove,   conceal   or   obliterate   any   copyright   or   other   proprietary
                                    notice or any credit-line or date-line on other mark or source identifier included on the
                                    Platform/ Service, including without limitation, the size, colour, location or style of
                                    all proprietary marks. Any infringement shall be vigorously defended and pursued 
                                    to the fullest extent permitted by law.</li>
                               </ol>
                            </li>
                            </div>
                            <div class='container'>
                            <li class="heading">
                                <h3>PRIVACY  POLICY</h3>
                                <ol>
                                    <li class="description">Company  is  committed  to  protecting  Your  Personal  Data.  Our  Privacy  Policy
                                        available on the Platform provides details about the information we collect about You,
                                        how we use it and how we protect it. It also explains Your rights and how to contact
                                        us if You have questions about how we use Your information, including Personal
                                        Data. Further, Company will, upon receipt of government order, or any order from the
                                        court   or   any   competent   authority   provide   information   or   assistance   to   authorized
                                        Government   agencies   for   verification   of   identity  or   traceability  of   the   User,   or
                                        prevention,  detection,  investigation,  prosecution,  cyber  security  incidents  and
                                        punishment of offences under any Applicable Law.</li>
                                </ol>
                            </li>
                            </div>
                            <div class='container'>
                            <li class="heading">
                                <h3>DISCLAIMER</h3>
                                <p>You  expressly  understand  and  agree  that,  to  the  maximum  extent  permitted  by 
                                    Applicable Law:</p>
                                <ol>
                                    <li class="description">The Platform is solely operated and managed by the Company.</li>
                                    <li class="description">The Services on the Platform are provided by the Company to the Users.</li>
                                    <li class="description">The Platform and other Content are provided by the Company on an “as is” basis
                                        without  warranty  of  any  kind,  express,  implied,  statutory,  or  otherwise,  including
                                        the  implied  warranties  of  title,  non-infringement,  merchantability,  or  fitness  for  a
                                        particular purpose. Without limiting the foregoing, the Company makes no warranty
                                        that the Platform or Services will meet Your requirements, or Your use of the Platform
                                        will be uninterrupted, timely, secure, or error-free. No advice or information, whether
                                        oral or written, obtained by You from the Company shall create any warranty not
                                        expressly stated in the Terms.</li>
                                    <li class="description">Company will not be liable for any loss that You may incur as a consequence of
                                        unauthorized use of Your User Account or User Account information in connection
                                        with the Platform either with or without Your knowledge.</li>
                                    <li class="description">Company has endeavoured to ensure that all the information on the Platform is correct,
                                        but   the   Company   neither   warrants   nor   makes   any   representations   regarding   the
                                        quality, accuracy or completeness of any data, information regarding the Services or
                                        otherwise. The Company shall not be responsible for the delay or inability to use the
                                        Platform  or  related  functionalities,  the  provision  of  or  failure  to  provide
                                        functionalities, or for any information, software, functionalities, and related graphics
                                        obtained through the Platform, or otherwise arising out of the use of the Platform,
                                        whether based on contract, tort, negligence, strict liability or otherwise. Further, the
                                        Company shall not be held responsible for non-availability of the Platform during
                                        periodic  maintenance  operations  or  any  unplanned  suspension  of  access  to  the
                                        Platform   that   may   occur   due   to   technical   reasons   or   for   any   reason   beyond   the
                                        Company’s reasonable control.</li>
                                    <li class="description">The Company shall have no liability whatsoever for any loss, damage that may be
                                        caused to You due to Your usage of the Platform and Services. Furthermore, in no
                                        event shall the Company’s total liability to You for all losses, damanges and causes
                                        of action exceed, in the aggregate, the amount paid by You, if any.</li>
                                </ol>
                            </li>
                            </div>
                            <div class='container'>
                            <li class="heading">
                                <h3>UPDATION / AMENDMENT</h3>
                                    <ol><li class="description">Company  can  update  this  or  any  other  related  policy  by  uploading  an  updated
                                        version  of  this  policy  on  the  Platform  or  any  click-through  format  which  would  be
                                        considered a consent of the User.</li>
                                        <li class="description">The   most   recent   version   of   this   or   any   other   policy   will   govern   the   use   of   the
                                          information on the Platform. We may revise or amend this from time to time. If we
                                            decide to change this or any other related policy, we will inform You by posting the
                                            revised policies on the Platform. Company may also, notify You of changes to the
                                            policies via email to the email address associated with Your User Account. If You
                                            object to any changes in this or any other related policy, You should immediately stop
                                      using the Platform and/or Services and close any related accounts. By continuing to
                                  access or use the Platform and/or Services after changes have become effective, You 
                                   agree to be bound by the revised amendments.</li>
                                  </ol>
                            </li>
                            </div>
                            <div class='container'>
                            <li class="heading">
                                <h3>MODIFICATIONS  TO  OR  TERMINATION  OF  THE  PLATFORM</h3>
                               <ol>
                                <li class="description"><b>Modification or Cessation</b>:
                                    Company  reserves  the  right   to,   at   any  time  and  from  time  to  time,   modify  or
                                    discontinue, temporarily or permanently, the Platform (or any part thereof), Services
                                    with or without notice and in its sole discretion. Users agree that the Company shall
                                    not   be   liable   to   the   User   or   any   third   party   for   any   modification,   suspension,   or
                                    discontinuance of the Services offered by the Company.</li>
                                <li class="description"><b>Termination by Company</b>:
                                    The Terms will continue to apply until terminated by either You or the Company as
                                    set forth below. If You object to the Terms or are dissatisfied with the Platform, You
                                    may   (i)   close   Your   User   Account   on   the   Platform;   and/or   (ii)   stop   accessing   the
                                    Platform. Furthermore, User hereby acknowledges and agree that the Company, in its
                                    sole  and  absolute  discretion,  has  the  right  (but  not  the  obligation)  to  delete,
                                    terminate, or deactivate User Account, block User’s email or IP address, cancel the
                                    Platform   or  otherwise   terminate   User’s   access   to   or   participation   in   the   use   of   the
                                    Platform (or any part thereof), or remove and discard any Content submitted by User
                                    on the Platform, immediately  and  without notice,  for any  reason, including  without
                                    limitation, User Account inactivity or if the Company believes or has reason to believe that the User
                                    has violated any provision of the Terms.  You shall be liable to pay any fees or charges,
                                    if applicable in respect of the Services until the date of termination by either party
                                    whatsoever.</li>
                                <li class="description"><b>Effect of Termination</b>:
                                    Upon termination of the User Account, User’s right to participate in the Platform shall
                                    stand terminated. In the event of termination, the User Account will be disabled and
                                    the User may not be granted access to the User Account or any other data contained
                                    in the User Account. Notwithstanding the foregoing, residual data may remain in
                                    Company’s system. Upon termination of Service, the User’s access to the Platform
                                    shall be immediately revoked. The provisions of these Terms which by their very
                                    nature are intended to survive termination shall survive expiration or termination of
                                    the Platform or User Account.</li>
                               </ol>
                            </li>
                            </div>
                             <div class='container'>
                                <li class="heading">
                                    <h3>MISCELLANEOUS</h3>
                                    <ol>
                                        <li class="description"><b>Charges for Services</b>:
                                            The  Company  may  charge  a  commission/fees  for  its   Services,  on  a  case  to  case
                                            basis  subject   to   the   User’s   add-on   requirement   over   and   above   the   basic   features   of
                                            Platform as decided by the Company from time to time.</li>
                                        <li class="description"><b>Advertisements</b>:
                                            The   Company   may   display   advertisements   and   promotions   on   the   Platform.   The
                                            manner,  mode,  and  extent  of  advertising  by  the  Company  on  the  Platform  are
                                            subject  to change and the appearance of advertisements on the Platform does not
                                            imply  endorsement by the Company of any advertised products or Services. The User
                                            agrees that the Company shall not be responsible or liable for any loss or damage of
                                            any  sort  incurred by the User as a result of any such dealings or as the result of the
                                            presence of such advertisers on the Platform.</li>
                                        <li class="description"><b>Communications</b>:
                                            You hereby expressly agree to receive communications by way of SMS, telephone
                                            calls, WhatsApp  /or  e-mails  from  the  Company  and  other third  parties  duly  authorised
                                            by the Company. You hereby expressly consent to the monitoring and recording, by
                                            the Company of any and all communications between You and the Company or its
                                            agents, employees, consultants, contractors, or representatives of the Company or of
                                            their authorised partners as per the Applicable Law. You can unsubscribe or opt-out
                                            from receiving communications through SMS and e-mail from the Company. In which
                                            case,   the   Company   will   only   send   You   communications   solely   required   for   the
                                            purposes of the Services provided through the Platform.</li>
                                        <li class="description"><b>Use of Cookies</b>:
                                            The Company uses cookies to aggregate information about the User’s sessions, 
                                            track information, store certain User preferences, analyse web page flow, etc. so that
                                            the Company can update and redesign the Company Platform, as necessary, to 
                                            provide User with the most useful information.<br>
                                            Users have the option to either accept or decline the use of cookies on their 
                                            computer/device, whether they are registered or not. However, a User’s experience of 
                                            the Platform shall be limited and certain features of the Platform will not be 
                                            available if the User declines the use of Cookies.</li>
                                        <li class="description"><b>Customer Care & Grievance Mechanism</b>:
                                            The User is hereby informed that in case of any queries relating to the Services, the
                                            User may contact the customer care, the details are mentioned 
                                            below:info@wahstory.com
                                            In the event the User has concerns / issues relating to the Services provided by 
                                            Company, the User is hereby informed that Company aims to provide You the best 
                                            experience and thereby, is fully committed to resolve all the issues faced by You in 
                                            relation to the Services we provide within 15 (fifteen) days from the date of receipt of 
                                            the complaint.
                                            To Address the queries/concerns of the Users, please note that we have a fully 
                                            committed redressal mechanism and that Your complaint shall be acknowledged with
                                            a period of 24 (twenty four) hours and the same be resolved within a period of 15 
                                            (fifteen) days. In this regard, kindly contact our grievance officer on the details 
                                            below: <br><br>
                                            <div class="description">
                                            Designation:  Marketing Manager<br>
                                            Email id: <a href="mailto:info@wahstory.com">info@wahstory.com</a></li>
                                        </div>
                                    </ol>
                                </li>
                            </div>
                     </ol>
                    </div>
        
    </div>
</div>

  
  <div class="cs-height_50 cs-height_lg_80"></div>
    <!-- Start CTA -->
    <?php include('footer.top.php');?>
     
    
  </body>
</html>