<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB; 

class IndustrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $industries = [
            ['industry' => 'Accounting'],
            ['industry' => 'Administrative Support'],
            ['industry' => 'Advertising'],
            ['industry' => 'Aerospace'],
            ['industry' => 'Aerospace Engineering'],
            ['industry' => 'Agriculture'],
            ['industry' => 'Animation'],
            ['industry' => 'Architecture'],
            ['industry' => 'Artificial Intelligence (AI)'],
            ['industry' => 'Auditing'],
            ['industry' => 'Automotive'],
            ['industry' => 'Banking'],
            ['industry' => 'Biotechnology'],
            ['industry' => 'Blockchain Development'],
            ['industry' => 'Business Analysis'],
            ['industry' => 'Business Development'],
            ['industry' => 'Civil Engineering'],
            ['industry' => 'Cloud Computing'],
            ['industry' => 'Commercial Real Estate'],
            ['industry' => 'Construction'],
            ['industry' => 'Consulting'],
            ['industry' => 'Content Writing'],
            ['industry' => 'Corporate Finance'],
            ['industry' => 'Corporate Strategy'],
            ['industry' => 'Crisis Management'],
            ['industry' => 'Customer Experience (CX)'],
            ['industry' => 'Customer Service'],
            ['industry' => 'Cybersecurity'],
            ['industry' => 'Data Analysis'],
            ['industry' => 'Database Management'],
            ['industry' => 'Digital Marketing'],
            ['industry' => 'E-commerce'],
            ['industry' => 'Education'],
            ['industry' => 'Electrical Engineering'],
            ['industry' => 'Energy'],
            ['industry' => 'Engineering'],
            ['industry' => 'Entertainment'],
            ['industry' => 'Entrepreneurship'],
            ['industry' => 'Environmental Health and Safety (EHS)'],
            ['industry' => 'Environmental Services'],
            ['industry' => 'Event Management'],
            ['industry' => 'Fashion & Apparel'],
            ['industry' => 'Fashion Design'],
            ['industry' => 'Film and Television Production'],
            ['industry' => 'Finance'],
            ['industry' => 'Financial Planning'],
            ['industry' => 'Fitness and Wellness'],
            ['industry' => 'Food and Beverage'],
            ['industry' => 'Game Development'],
            ['industry' => 'Government'],
            ['industry' => 'Graphic Design'],
            ['industry' => 'Healthcare'],
            ['industry' => 'Healthcare Administration'],
            ['industry' => 'Hospitality'],
            ['industry' => 'Human Resources (HR)'],
            ['industry' => 'Human Resources Compliance'],
            ['industry' => 'Human Resources Operations'],
            ['industry' => 'Industrial Design'],
            ['industry' => 'Information Technology (IT)'],
            ['industry' => 'Insurance'],
            ['industry' => 'Interior Design'],
            ['industry' => 'Investment Banking'],
            ['industry' => 'Investment Management'],
            ['industry' => 'IT Support'],
            ['industry' => 'Law Enforcement'],
            ['industry' => 'Legal'],
            ['industry' => 'Legal Compliance'],
            ['industry' => 'Legal Services'],
            ['industry' => 'Logistics'],
            ['industry' => 'Manufacturing'],
            ['industry' => 'Market Research'],
            ['industry' => 'Marketing'],
            ['industry' => 'Mechanical Engineering'],
            ['industry' => 'Media'],
            ['industry' => 'Media and Communications'],
            ['industry' => 'Medical Coding'],
            ['industry' => 'Medical Research'],
            ['industry' => 'Mobile App Development'],
            ['industry' => 'Music Production'],
            ['industry' => 'Network Administration'],
            ['industry' => 'Nonprofit'],
            ['industry' => 'Non-Profit'],
            ['industry' => 'Operations Management'],
            ['industry' => 'Pharmaceutical'],
            ['industry' => 'Pharmaceutical Sales'],
            ['industry' => 'Pharmaceuticals'],
            ['industry' => 'Photography'],
            ['industry' => 'Procurement'],
            ['industry' => 'Product Management'],
            ['industry' => 'Project Management'],
            ['industry' => 'Property Management'],
            ['industry' => 'Public Health'],
            ['industry' => 'Public Relations'],
            ['industry' => 'Quality Assurance'],
            ['industry' => 'Real Estate'],
            ['industry' => 'Renewable Energy'],
            ['industry' => 'Research and Development (R&D)'],
            ['industry' => 'Retail'],
            ['industry' => 'Risk Management'],
            ['industry' => 'Sales'],
            ['industry' => 'Sales Engineering'],
            ['industry' => 'Sales Management'],
            ['industry' => 'Social Media Management'],
            ['industry' => 'Software Development'],
            ['industry' => 'Startups'],
            ['industry' => 'Supply Chain Management'],
            ['industry' => 'Technical Support'],
            ['industry' => 'Technical Writing'],
            ['industry' => 'Technology'],
            ['industry' => 'Telecommunications'],
            ['industry' => 'Tourism'],
            ['industry' => 'Training and Development (HR)'],
            ['industry' => 'Transportation'],
            ['industry' => 'UX/UI Design'],
            ['industry' => 'Video Editing'],
            ['industry' => 'Wealth Management'],
            ['industry' => 'Web Development'],
            ['industry' => 'Coach'],
            ['industry' => 'Doctor'],
            ['industry' => 'Other'],
        ];
        DB::table('industries')->insert($industries);
    }
}
