<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB; 

class SkillsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $skills = [
            ['skill' => 'Business Strategy & Development', 'description' => ''],
            ['skill' => 'Fundraising & Investor Relations', 'description' => ''],
            ['skill' => 'Startups & Entrepreneurship', 'description' => ''],
            ['skill' => 'Visionary Leadership', 'description' => ''],
            ['skill' => 'Product Development', 'description' => ''],
            ['skill' => 'Market Penetration Strategy', 'description' => ''],
            ['skill' => 'Bootstrapping & Scaling', 'description' => ''],
            ['skill' => 'Pitching & Presentation Skills', 'description' => ''],
            ['skill' => 'Business Model Innovation', 'description' => ''],
            ['skill' => 'Competitive Analysis', 'description' => ''],
            ['skill' => 'Partnership Development', 'description' => ''],
            ['skill' => 'Exit Strategy Planning', 'description' => ''],
            ['skill' => 'Agile Business Management', 'description' => ''],
            ['skill' => 'Venture Capital & Angel Investment', 'description' => ''],
            ['skill' => 'Startup Ecosystem Networking', 'description' => ''],
            ['skill' => 'Cross-cultural Communication', 'description' => ''],
            ['skill' => 'International Business Strategy', 'description' => ''],
            ['skill' => 'Global Market Trends', 'description' => ''],
            ['skill' => 'Networking with International Alumni', 'description' => ''],
            ['skill' => 'Adaptability & Cultural Sensitivity', 'description' => ''],
            ['skill' => 'Foreign Languages & Multilingual Skills', 'description' => ''],
            ['skill' => 'Cross-border Negotiation Skills', 'description' => ''],
            ['skill' => 'Study Abroad Advising', 'description' => ''],
            ['skill' => 'International Student Recruitment', 'description' => ''],
            ['skill' => 'Research Methodologies (Specific to Academic Discipline)', 'description' => ''],
            ['skill' => 'International Trade & Commerce', 'description' => ''],
            ['skill' => 'Global Leadership', 'description' => ''],
            ['skill' => 'Cultural Exchange Programs', 'description' => ''],
            ['skill' => 'Understanding International Regulatory Compliance', 'description' => ''],
            ['skill' => 'Cross-border Mergers & Acquisitions', 'description' => ''],
            ['skill' => 'Executive Coaching', 'description' => ''],
            ['skill' => 'Career Coaching & Guidance', 'description' => ''],
            ['skill' => 'Leadership Development', 'description' => ''],
            ['skill' => 'Life Coaching & Personal Development', 'description' => ''],
            ['skill' => 'Emotional Intelligence (EQ)', 'description' => ''],
            ['skill' => 'Mindfulness & Stress Management', 'description' => ''],
            ['skill' => 'Performance Improvement', 'description' => ''],
            ['skill' => 'Goal Setting & Achievement', 'description' => ''],
            ['skill' => 'Coaching for Startups & Entrepreneurs', 'description' => ''],
            ['skill' => 'Public Speaking Coaching', 'description' => ''],
            ['skill' => 'Motivational Speaking', 'description' => ''],
            ['skill' => 'Time Management', 'description' => ''],
            ['skill' => 'Team Building & Coaching', 'description' => ''],
            ['skill' => 'Accountability Partnership', 'description' => ''],
            ['skill' => 'Conflict Resolution Coaching', 'description' => ''],
            ['skill' => 'Brand Collaboration & Sponsorship', 'description' => ''],
            ['skill' => 'Content Strategy', 'description' => ''],
            ['skill' => 'Social Media Strategy (Instagram, TikTok, YouTube)', 'description' => ''],
            ['skill' => 'Video Production & Editing', 'description' => ''],
            ['skill' => 'Community Building', 'description' => ''],
            ['skill' => 'Influencer Marketing', 'description' => ''],
            ['skill' => 'Digital Storytelling', 'description' => ''],
            ['skill' => 'Personal Branding', 'description' => ''],
            ['skill' => 'Audience Engagement', 'description' => ''],
            ['skill' => 'Trend Analysis & Adaptation', 'description' => ''],
            ['skill' => 'Podcast Hosting & Production', 'description' => ''],
            ['skill' => 'Affiliate Marketing', 'description' => ''],
            ['skill' => 'Creative Direction', 'description' => ''],
            ['skill' => 'Viral Marketing Techniques', 'description' => ''],
            ['skill' => 'Analytics & Social Media Metrics', 'description' => ''],
            ['skill' => 'Architectural Design', 'description' => ''],
            ['skill' => 'Urban Planning & Development', 'description' => ''],
            ['skill' => 'CAD Software (AutoCAD, Revit)', 'description' => ''],
            ['skill' => 'Sustainable Architecture', 'description' => ''],
            ['skill' => 'Building Information Modeling (BIM)', 'description' => ''],
            ['skill' => 'Landscape Architecture', 'description' => ''],
            ['skill' => 'Interior Design', 'description' => ''],
            ['skill' => 'Urban Design & Master Planning', 'description' => ''],
            ['skill' => 'LEED Certification & Green Building', 'description' => ''],
            ['skill' => 'Project Feasibility Analysis', 'description' => ''],
            ['skill' => 'Zoning & Permitting', 'description' => ''],
            ['skill' => 'Historic Preservation', 'description' => ''],
            ['skill' => 'Construction Management', 'description' => ''],
            ['skill' => '3D Visualization & Rendering', 'description' => ''],
            ['skill' => 'Structural Analysis', 'description' => ''],
            ['skill' => 'Clinical Diagnosis & Treatment', 'description' => ''],
            ['skill' => 'Patient Care & Consultation', 'description' => ''],
            ['skill' => 'Medical Research & Publication', 'description' => ''],
            ['skill' => 'Surgery & Post-operative Care', 'description' => ''],
            ['skill' => 'Telemedicine & Remote Consultation', 'description' => ''],
            ['skill' => 'Specialized Treatments (e.g., Cardiology, Neurology)', 'description' => ''],
            ['skill' => 'Healthcare Management & Administration', 'description' => ''],
            ['skill' => 'Electronic Medical Records (EMR)', 'description' => ''],
            ['skill' => 'Public Health Advocacy', 'description' => ''],
            ['skill' => 'Medical Education & Training', 'description' => ''],
            ['skill' => 'Palliative Care', 'description' => ''],
            ['skill' => 'Emergency Medicine', 'description' => ''],
            ['skill' => 'Health Informatics', 'description' => ''],
            ['skill' => 'Medical Device Proficiency', 'description' => ''],
            ['skill' => 'Disease Prevention & Management', 'description' => ''],
            ['skill' => 'Curriculum Design & Development', 'description' => ''],
            ['skill' => 'Educational Policy Analysis', 'description' => ''],
            ['skill' => 'Pedagogical Strategies', 'description' => ''],
            ['skill' => 'Classroom Technology Integration', 'description' => ''],
            ['skill' => 'Research & Publication in Education', 'description' => ''],
            ['skill' => 'Student Counseling & Support', 'description' => ''],
            ['skill' => 'STEM Education', 'description' => ''],
            ['skill' => 'Special Education Expertise', 'description' => ''],
            ['skill' => 'Online Learning Platforms (LMS)', 'description' => ''],
            ['skill' => 'Teacher Training & Development', 'description' => ''],
            ['skill' => 'Educational Leadership', 'description' => ''],
            ['skill' => 'Academic Writing & Research', 'description' => ''],
            ['skill' => 'Early Childhood Education', 'description' => ''],
            ['skill' => 'Literacy Program Development', 'description' => ''],
            ['skill' => 'Education Reform Advocacy', 'description' => ''],
            ['skill' => 'Corporate Law & Compliance', 'description' => ''],
            ['skill' => 'Intellectual Property Rights (IPR)', 'description' => ''],
            ['skill' => 'Contract Drafting & Negotiation', 'description' => ''],
            ['skill' => 'Litigation & Dispute Resolution', 'description' => ''],
            ['skill' => 'Mergers & Acquisitions (M&A)', 'description' => ''],
            ['skill' => 'International Law & Trade', 'description' => ''],
            ['skill' => 'Data Privacy & Cybersecurity Law', 'description' => ''],
            ['skill' => 'Employment Law', 'description' => ''],
            ['skill' => 'Real Estate Law', 'description' => ''],
            ['skill' => 'Environmental Law', 'description' => ''],
            ['skill' => 'Arbitration & Mediation', 'description' => ''],
            ['skill' => 'Immigration Law', 'description' => ''],
            ['skill' => 'Legal Advisory for Startups', 'description' => ''],
            ['skill' => 'Compliance Audits', 'description' => ''],
            ['skill' => 'Public Policy & Legislative Advocacy', 'description' => ''],
            ['skill' => 'Business Process Re-engineering (BPR)', 'description' => ''],
            ['skill' => 'Strategy Consulting', 'description' => ''],
            ['skill' => 'Change Management Consulting', 'description' => ''],
            ['skill' => 'Market Entry Strategy', 'description' => ''],
            ['skill' => 'Digital Transformation', 'description' => ''],
            ['skill' => 'IT Consulting & Systems Integration', 'description' => ''],
            ['skill' => 'Lean & Six Sigma Certification', 'description' => ''],
            ['skill' => 'ERP Implementation (SAP, Oracle)', 'description' => ''],
            ['skill' => 'Organizational Development', 'description' => ''],
            ['skill' => 'Performance Analytics', 'description' => ''],
            ['skill' => 'Financial Consulting & Advisory', 'description' => ''],
            ['skill' => 'Customer Experience Strategy', 'description' => ''],
            ['skill' => 'Operational Efficiency Consulting', 'description' => ''],
            ['skill' => 'Data-Driven Decision Making', 'description' => ''],
            ['skill' => 'Governance, Risk, and Compliance (GRC)', 'description' => ''],
            ['skill' => 'Art Direction & Visual Identity', 'description' => ''],
            ['skill' => 'Copywriting & Creative Writing', 'description' => ''],
            ['skill' => 'UX/UI Design', 'description' => ''],
            ['skill' => 'User-Centered Design', 'description' => ''],
            ['skill' => 'Branding & Identity Design', 'description' => ''],
            ['skill' => 'Photography & Retouching', 'description' => ''],
            ['skill' => 'Animation & 3D Modeling', 'description' => ''],
            ['skill' => 'Graphic Design (Adobe Illustrator, Photoshop)', 'description' => ''],
            ['skill' => 'Fashion Design & Styling', 'description' => ''],
            ['skill' => 'Voiceover & Narration', 'description' => ''],
            ['skill' => 'Scriptwriting for Film & TV', 'description' => ''],
            ['skill' => 'Illustration & Character Design', 'description' => ''],
            ['skill' => 'Interior Design & Space Planning', 'description' => ''],
            ['skill' => 'Calligraphy & Hand Lettering', 'description' => ''],
            ['skill' => 'Curating Art Exhibitions', 'description' => ''],
            ['skill' => 'Real Estate Investment Strategy', 'description' => ''],
            ['skill' => 'Property Valuation & Appraisal', 'description' => ''],
            ['skill' => 'Commercial & Residential Sales', 'description' => ''],
            ['skill' => 'Lease Negotiation & Contract Management', 'description' => ''],
            ['skill' => 'Real Estate Marketing & Branding', 'description' => ''],
            ['skill' => 'Real Estate Development', 'description' => ''],
            ['skill' => 'Property Management & Leasing', 'description' => ''],
            ['skill' => 'Market Analysis & Feasibility Studies', 'description' => ''],
            ['skill' => 'Real Estate Financing', 'description' => ''],
            ['skill' => 'Tenant Relations & Management', 'description' => ''],
            ['skill' => 'Real Estate Technology (PropTech)', 'description' => ''],
            ['skill' => 'Building and Land Regulations', 'description' => ''],
            ['skill' => 'Luxury Real Estate Sales', 'description' => ''],
            ['skill' => 'Facility Management', 'description' => ''],
            ['skill' => 'Community Development', 'description' => ''],
            ['skill' => 'Public Speaking & Keynote Address', 'description' => ''],
            ['skill' => 'Thought Leadership Content', 'description' => ''],
            ['skill' => 'Media Appearances & Interviews', 'description' => ''],
            ['skill' => 'Community Engagement', 'description' => ''],
            ['skill' => 'Opinion Writing & Editorials', 'description' => ''],
            ['skill' => 'Non-Profit Leadership & Advocacy', 'description' => ''],
            ['skill' => 'Event Hosting & Moderation', 'description' => ''],
            ['skill' => 'Networking & Mentorship', 'description' => ''],
            ['skill' => 'Corporate Social Responsibility (CSR)', 'description' => ''],
            ['skill' => 'Strategy Advisory for Organizations', 'description' => ''],
            ['skill' => 'Research & Innovation', 'description' => ''],
            ['skill' => 'Panel Discussions & Webinars', 'description' => ''],
            ['skill' => 'Brand Ambassadorship', 'description' => ''],
            ['skill' => 'Diplomacy & International Relations', 'description' => ''],
            ['skill' => 'Policy Analysis & Public Affairs', 'description' => ''],
            ['skill' => 'Team Leadership', 'description' => ''],
            ['skill' => 'Project Management', 'description' => ''],
            ['skill' => 'Strategic Planning', 'description' => ''],
            ['skill' => 'Operations Management', 'description' => ''],
            ['skill' => 'Cross-functional Team Management', 'description' => ''],
            ['skill' => 'Change Management', 'description' => ''],
            ['skill' => 'People Management', 'description' => ''],
            ['skill' => 'Conflict Resolution', 'description' => ''],
            ['skill' => 'Stakeholder Management', 'description' => ''],
            ['skill' => 'Agile Methodology', 'description' => ''],
            ['skill' => 'Program Management', 'description' => ''], 
            ['skill' => 'Executive Management', 'description' => ''],
            ['skill' => 'Decision-Making', 'description' => ''],
            ['skill' => 'Risk Management', 'description' => ''],
            ['skill' => 'Process Optimization', 'description' => ''],
            ['skill' => 'Sales Strategy', 'description' => ''],
            ['skill' => 'Business Development', 'description' => ''],
            ['skill' => 'B2B Sales', 'description' => ''],
            ['skill' => 'B2C Sales', 'description' => ''],
            ['skill' => 'Customer Relationship Management (CRM)', 'description' => ''],
            ['skill' => 'Lead Generation', 'description' => ''],
            ['skill' => 'Sales Management', 'description' => ''],
            ['skill' => 'Account Management', 'description' => ''],
            ['skill' => 'Negotiation', 'description' => ''],
            ['skill' => 'Sales Forecasting', 'description' => ''],
            ['skill' => 'Market Expansion', 'description' => ''],
            ['skill' => 'Cold Calling', 'description' => ''],
            ['skill' => 'Consultative Selling', 'description' => ''],
            ['skill' => 'Retail Sales', 'description' => ''],
            ['skill' => 'Sales Coaching & Training', 'description' => ''],
            ['skill' => 'Talent Acquisition', 'description' => ''],
            ['skill' => 'Recruitment Strategy', 'description' => ''],
            ['skill' => 'Employee Engagement', 'description' => ''],
            ['skill' => 'HR Consulting', 'description' => ''], 
            ['skill' => 'Training & Development', 'description' => ''],
            ['skill' => 'Performance Management', 'description' => ''],
            ['skill' => 'Diversity & Inclusion', 'description' => ''],
            ['skill' => 'Compensation & Benefits', 'description' => ''],
            ['skill' => 'HR Policy Formulation', 'description' => ''],
            ['skill' => 'Succession Planning', 'description' => ''],
            ['skill' => 'Employee Relations', 'description' => ''],
            ['skill' => 'Labor Law Compliance', 'description' => ''],
            ['skill' => 'Onboarding', 'description' => ''],
            ['skill' => 'Workforce Planning', 'description' => ''],
            ['skill' => 'Digital Strategy', 'description' => ''],
            ['skill' => 'Social Media Marketing', 'description' => ''],
            ['skill' => 'Content Marketing', 'description' => ''],
            ['skill' => 'SEO/SEM', 'description' => ''],
            ['skill' => 'Brand Management', 'description' => ''],
            ['skill' => 'Email Marketing', 'description' => ''],
            ['skill' => 'Market Research', 'description' => ''],
            ['skill' => 'Influencer Marketing', 'description' => ''],
            ['skill' => 'Paid Media (PPC)', 'description' => ''],
            ['skill' => 'Marketing Analytics', 'description' => ''],
            ['skill' => 'Growth Hacking', 'description' => ''],
            ['skill' => 'Product Marketing', 'description' => ''],
            ['skill' => 'E-commerce Marketing', 'description' => ''],
            ['skill' => 'Copywriting & Editing', 'description' => ''],
            ['skill' => 'Public Relations (PR)', 'description' => ''],
            ['skill' => 'Advertising Campaigns', 'description' => ''],
            ['skill' => 'Software Development', 'description' => ''],
            ['skill' => 'Cloud Computing (AWS, Azure, Google Cloud)', 'description' => ''],
            ['skill' => 'Cybersecurity', 'description' => ''],
            ['skill' => 'Data Analysis', 'description' => ''],
            ['skill' => 'IT Strategy', 'description' => ''],
            ['skill' => 'Network Administration', 'description' => ''],
            ['skill' => 'DevOps', 'description' => ''],
            ['skill' => 'Web Development (HTML, CSS, JavaScript)', 'description' => ''],
            ['skill' => 'Database Management (SQL, NoSQL)', 'description' => ''],
            ['skill' => 'System Architecture', 'description' => ''],
            ['skill' => 'AI & Machine Learning', 'description' => ''],
            ['skill' => 'Mobile Application Development', 'description' => ''],
            ['skill' => 'Blockchain Development', 'description' => ''],
            ['skill' => 'Software Testing & QA', 'description' => ''],
            ['skill' => 'User Experience (UX) Design', 'description' => ''],
            ['skill' => 'Financial Analysis', 'description' => ''],
            ['skill' => 'Budgeting & Forecasting', 'description' => ''],
            ['skill' => 'Accounting', 'description' => ''],
            ['skill' => 'Taxation', 'description' => ''],
            ['skill' => 'Financial Reporting', 'description' => ''],
            ['skill' => 'Risk Management', 'description' => ''],
            ['skill' => 'Investment Management', 'description' => ''],
            ['skill' => 'Cost Management', 'description' => ''],
            ['skill' => 'Mergers & Acquisitions (M&A)', 'description' => ''],
            ['skill' => 'Corporate Finance', 'description' => ''],
            ['skill' => 'Treasury Management', 'description' => ''],
            ['skill' => 'Audit & Compliance', 'description' => ''],
            ['skill' => 'Financial Planning & Analysis (FP&A)', 'description' => ''],
            ['skill' => 'Credit Analysis', 'description' => ''],
            ['skill' => 'Capital Markets', 'description' => ''],
            ['skill' => 'Customer Relationship Management (CRM)', 'description' => ''],
            ['skill' => 'Customer Experience (CX)', 'description' => ''],
            ['skill' => 'Client Management', 'description' => ''],
            ['skill' => 'Customer Retention', 'description' => ''],
            ['skill' => 'Technical Support', 'description' => ''],
            ['skill' => 'Problem-Solving', 'description' => ''],
            ['skill' => 'Communication', 'description' => ''],
            ['skill' => 'Help Desk Support', 'description' => ''],
            ['skill' => 'Call Center Management', 'description' => ''],
            ['skill' => 'Complaint Resolution', 'description' => ''],
            ['skill' => 'Customer Success', 'description' => ''],
            ['skill' => 'Service Level Agreements (SLAs)', 'description' => ''],
            ['skill' => 'Empathy & Active Listening', 'description' => ''],
            ['skill' => 'Multi-channel Support (Email, Chat, Phone)', 'description' => ''],
            ['skill' => 'Customer Satisfaction (CSAT)', 'description' => ''],
            ['skill' => 'Supply Chain Management', 'description' => ''],
            ['skill' => 'Logistics Management', 'description' => ''],
            ['skill' => 'Inventory Management', 'description' => ''],
            ['skill' => 'Lean Manufacturing', 'description' => ''],
            ['skill' => 'Quality Control', 'description' => ''],
            ['skill' => 'Process Improvement', 'description' => ''],
            ['skill' => 'Procurement', 'description' => ''],
            ['skill' => 'Distribution & Warehousing', 'description' => ''],
            ['skill' => 'Demand Planning', 'description' => ''],
            ['skill' => 'Vendor Management', 'description' => ''],
            ['skill' => 'Import/Export Compliance', 'description' => ''],
            ['skill' => 'Manufacturing Operations', 'description' => ''],
            ['skill' => 'Fleet Management', 'description' => ''],
            ['skill' => 'Six Sigma', 'description' => ''],
            ['skill' => 'Order Fulfillment', 'description' => ''],
            ['skill' => 'Graphic Design', 'description' => ''],
            ['skill' => 'Video Editing', 'description' => ''],
            ['skill' => 'Content Creation', 'description' => ''],
            ['skill' => 'UX/UI Design', 'description' => ''],
            ['skill' => 'Photography', 'description' => ''],
            ['skill' => 'Animation & Motion Graphics', 'description' => ''],
            ['skill' => 'Art Direction', 'description' => ''],
            ['skill' => 'Web Design', 'description' => ''],
            ['skill' => 'Storyboarding', 'description' => ''],
            ['skill' => 'Creative Writing', 'description' => ''],
            ['skill' => 'Branding', 'description' => ''],
            ['skill' => 'Copywriting', 'description' => ''],
            ['skill' => 'Adobe Creative Suite (Photoshop, Illustrator, Premiere Pro)', 'description' => ''],
            ['skill' => 'Podcast Production', 'description' => ''],
            ['skill' => 'Illustration', 'description' => ''],
            ['skill' => 'Data Visualization (Tableau, Power BI)', 'description' => ''],
            ['skill' => 'Machine Learning', 'description' => ''],
            ['skill' => 'Statistical Analysis', 'description' => ''],
            ['skill' => 'Business Intelligence (BI)', 'description' => ''],
            ['skill' => 'Big Data Analytics', 'description' => ''],
            ['skill' => 'Predictive Analytics', 'description' => ''],
            ['skill' => 'SQL/R/Python', 'description' => ''],
            ['skill' => 'Natural Language Processing (NLP)', 'description' => ''],
            ['skill' => 'Data Engineering', 'description' => ''],
            ['skill' => 'Data Mining', 'description' => ''],
            ['skill' => 'A/B Testing', 'description' => ''],
            ['skill' => 'Deep Learning', 'description' => ''],
            ['skill' => 'Data Cleaning & Preprocessing', 'description' => ''],
            ['skill' => 'Time Series Analysis', 'description' => ''],
            ['skill' => 'AI Model Deployment', 'description' => ''],
            ['skill' => 'Mechanical Engineering', 'description' => ''],
            ['skill' => 'Electrical Engineering', 'description' => ''],
            ['skill' => 'Civil Engineering', 'description' => ''],
            ['skill' => 'CAD Software (AutoCAD, SolidWorks)', 'description' => ''],
            ['skill' => 'Product Design & Development', 'description' => ''],
            ['skill' => 'Electronics Circuit Design', 'description' => ''],
            ['skill' => 'Robotics', 'description' => ''],
            ['skill' => 'Structural Engineering', 'description' => ''],
            ['skill' => 'Quality Assurance (QA)', 'description' => ''],
            ['skill' => 'Automation', 'description' => ''],
            ['skill' => 'HVAC Systems', 'description' => ''],
            ['skill' => 'Industrial Engineering', 'description' => ''],
            ['skill' => '3D Printing & Prototyping', 'description' => ''],
            ['skill' => 'Maintenance Management', 'description' => ''],
            ['skill' => 'Power Systems', 'description' => ''],
            ['skill' => 'Clinical Research', 'description' => ''],
            ['skill' => 'Patient Care', 'description' => ''],
            ['skill' => 'Healthcare Management', 'description' => ''],
            ['skill' => 'Medical Coding & Billing', 'description' => ''],
            ['skill' => 'Nursing', 'description' => ''],
            ['skill' => 'Telemedicine', 'description' => ''],
            ['skill' => 'Public Health', 'description' => ''],
            ['skill' => 'Medical Writing', 'description' => ''],
            ['skill' => 'Pharmaceutical Sales', 'description' => ''],
            ['skill' => 'EMR/EHR Systems', 'description' => ''],
            ['skill' => 'Health Informatics', 'description' => ''],
            ['skill' => 'Mental Health Counseling', 'description' => ''],
            ['skill' => 'Medical Device Sales', 'description' => ''],
            ['skill' => 'Nutrition & Dietetics', 'description' => ''],
            ['skill' => 'Rehabilitation Therapy', 'description' => ''],
            ['skill' => 'Corporate Law', 'description' => ''],
            ['skill' => 'Contract Negotiation', 'description' => ''],
            ['skill' => 'Intellectual Property (IP) Law', 'description' => ''],
            ['skill' => 'Labor & Employment Law', 'description' => ''],
            ['skill' => 'Legal Research', 'description' => ''],
            ['skill' => 'Litigation', 'description' => ''],
            ['skill' => 'Risk Compliance', 'description' => ''],
            ['skill' => 'Regulatory Affairs', 'description' => ''],
            ['skill' => 'Mergers & Acquisitions (M&A)', 'description' => ''],
            ['skill' => 'Legal Drafting', 'description' => ''],
            ['skill' => 'Data Privacy & GDPR', 'description' => ''],
            ['skill' => 'Anti-Money Laundering (AML)', 'description' => ''],
            ['skill' => 'Due Diligence', 'description' => ''],
            ['skill' => 'Mediation & Arbitration', 'description' => ''],
            ['skill' => 'Legal Writing', 'description' => ''],
            ['skill' => 'Curriculum Development', 'description' => ''],
            ['skill' => 'Instructional Design', 'description' => ''],
            ['skill' => 'E-Learning', 'description' => ''],
            ['skill' => 'Corporate Training', 'description' => ''],
            ['skill' => 'Public Speaking', 'description' => ''],
            ['skill' => 'Coaching & Mentoring', 'description' => ''],
            ['skill' => 'Classroom Management', 'description' => ''],
            ['skill' => 'Adult Learning Theory', 'description' => ''],
            ['skill' => 'Educational Technology', 'description' => ''],
            ['skill' => 'Learning Management Systems (LMS)', 'description' => ''],
            ['skill' => 'Academic Writing', 'description' => ''],
            ['skill' => 'Soft Skills Training', 'description' => ''],
            ['skill' => 'Workshop Facilitation', 'description' => ''],
            ['skill' => 'Student Counseling', 'description' => ''],
            ['skill' => 'Tutoring', 'description' => ''],
            ['skill' => 'Real Estate Investment', 'description' => ''],
            ['skill' => 'Property Management', 'description' => ''],
            ['skill' => 'Lease Administration', 'description' => ''],
            ['skill' => 'Commercial Real Estate', 'description' => ''],
            ['skill' => 'Residential Sales', 'description' => ''],
            ['skill' => 'Real Estate Development', 'description' => ''],
            ['skill' => 'Real Estate Appraisal', 'description' => ''],
            ['skill' => 'Negotiation & Deal Closing', 'description' => ''],
            ['skill' => 'Market Analysis', 'description' => ''],
            ['skill' => 'Facility Management', 'description' => ''],
            ['skill' => 'Property Inspections', 'description' => ''],
            ['skill' => 'Tenant Relations', 'description' => ''],
            ['skill' => 'Land Acquisition', 'description' => ''],
            ['skill' => 'Real Estate Marketing', 'description' => ''],
            ['skill' => 'Zoning & Permitting', 'description' => ''],
            ['skill' => 'Public Relations (PR)', 'description' => ''],
            ['skill' => 'Media Relations', 'description' => ''],
            ['skill' => 'Copywriting & Editing', 'description' => ''],
            ['skill' => 'Social Media Strategy', 'description' => ''],
            ['skill' => 'Journalism', 'description' => ''],
            ['skill' => 'Broadcasting', 'description' => ''],
            ['skill' => 'Storytelling', 'description' => ''],
            ['skill' => 'Event Planning', 'description' => ''],
            ['skill' => 'Corporate Communications', 'description' => ''],
            ['skill' => 'Crisis Communication', 'description' => ''],
            ['skill' => 'Video Production', 'description' => ''],
            ['skill' => 'Podcasting', 'description' => ''],
            ['skill' => 'Media Buying & Planning', 'description' => ''],
            ['skill' => 'Scriptwriting', 'description' => ''],
            ['skill' => 'Influencer Relations', 'description' => ''],
            ['skill' => 'Environmental Impact Assessment', 'description' => ''],
            ['skill' => 'Sustainability Consulting', 'description' => ''],
            ['skill' => 'Renewable Energy', 'description' => ''],
            ['skill' => 'Climate Change Mitigation', 'description' => ''],
            ['skill' => 'Energy Management', 'description' => ''],
            ['skill' => 'Waste Management', 'description' => ''],
            ['skill' => 'Water Resource Management', 'description' => ''],
            ['skill' => 'Environmental Policy', 'description' => ''],
            ['skill' => 'Corporate Social Responsibility (CSR)', 'description' => ''],
            ['skill' => 'Sustainable Supply Chain', 'description' => ''],
            ['skill' => 'Environmental Health & Safety (EHS)', 'description' => ''],
            ['skill' => 'Carbon Footprint Reduction', 'description' => ''],
            ['skill' => 'Circular Economy', 'description' => ''],
            ['skill' => 'Green Building Design (LEED)', 'description' => ''],
            ['skill' => 'Biodiversity Conservation', 'description' => ''],
            ['skill' => 'Holistic Health Coaching', 'description' => ''],
            ['skill' => 'Mindfulness & Meditation', 'description' => ''],
            ['skill' => 'Yoga Instruction (Hatha, Vinyasa, Ashtanga, etc.)', 'description' => ''],
            ['skill' => 'Fitness Training & Personal Training', 'description' => ''],
            ['skill' => 'Nutritional Counseling', 'description' => ''],
            ['skill' => 'Stress Management Techniques', 'description' => ''],
            ['skill' => 'Lifestyle Medicine', 'description' => ''],
            ['skill' => 'Emotional Wellness', 'description' => ''],
            ['skill' => 'Habit Formation & Behavior Change', 'description' => ''],
            ['skill' => 'Wellness Retreat Planning', 'description' => ''],
            ['skill' => 'Wellness Program Design', 'description' => ''],
            ['skill' => 'Sleep Coaching & Optimization', 'description' => ''],
            ['skill' => 'Breathwork Techniques', 'description' => ''],
            ['skill' => 'Corporate Wellness Programs', 'description' => ''],
            ['skill' => 'Work-Life Balance Coaching', 'description' => ''],
            ['skill' => 'Ayurveda & Traditional Medicine', 'description' => ''],
            ['skill' => 'Aromatherapy', 'description' => ''],
            ['skill' => 'Reiki Healing', 'description' => ''],
            ['skill' => 'Acupuncture & Acupressure', 'description' => ''],
            ['skill' => 'Herbal Medicine', 'description' => ''],
            ['skill' => 'Homeopathy', 'description' => ''],
            ['skill' => 'Sound Healing & Therapy', 'description' => ''],
            ['skill' => 'Reflexology', 'description' => ''],
            ['skill' => 'Energy Healing', 'description' => ''],
            ['skill' => 'Chakra Balancing', 'description' => ''],
            ['skill' => 'Tai Chi & Qigong', 'description' => ''],
            ['skill' => 'Naturopathy', 'description' => ''],
            ['skill' => 'Crystal Healing', 'description' => ''],
            ['skill' => 'Massage Therapy Techniques (Swedish, Deep Tissue, Thai)', 'description' => ''],
            ['skill' => 'Detoxification Programs', 'description' => ''],
            ['skill' => 'Positive Psychology', 'description' => ''],
            ['skill' => 'Cognitive Behavioral Therapy (CBT) Techniques', 'description' => ''],
            ['skill' => 'Emotional Intelligence Development', 'description' => ''],
            ['skill' => 'Life Purpose Coaching', 'description' => ''],
            ['skill' => 'Art Therapy', 'description' => ''],
            ['skill' => 'Somatic Healing', 'description' => ''],
            ['skill' => 'Self-Care Coaching', 'description' => ''],
            ['skill' => 'Grief Counseling & Support', 'description' => ''],
            ['skill' => 'Emotional Resilience Training', 'description' => ''],
            ['skill' => 'Mind-Body Connection Practices', 'description' => ''],
            ['skill' => 'Journaling for Mental Clarity', 'description' => ''],
            ['skill' => 'Group Therapy & Support Groups', 'description' => ''],
            ['skill' => 'Mental Health Advocacy', 'description' => ''],
            ['skill' => 'Guided Imagery & Visualization', 'description' => ''],
            ['skill' => 'Trauma-Informed Care', 'description' => ''],
            ['skill' => 'Plant-Based Nutrition', 'description' => ''],
            ['skill' => 'Sports Nutrition', 'description' => ''],
            ['skill' => 'Weight Management Programs', 'description' => ''],
            ['skill' => 'Gut Health & Microbiome Balancing', 'description' => ''],
            ['skill' => 'Detox Diet Planning', 'description' => ''],
            ['skill' => 'Meal Planning & Prep Coaching', 'description' => ''],
            ['skill' => 'Keto, Paleo, and Other Diet Plans', 'description' => ''],
            ['skill' => 'Food Sensitivity & Allergy Management', 'description' => ''],
            ['skill' => 'Integrative Nutrition', 'description' => ''],
            ['skill' => 'Functional Nutrition', 'description' => ''],
            ['skill' => 'Anti-Inflammatory Diet Planning', 'description' => ''],
            ['skill' => 'Dietary Supplements & Herbal Remedies', 'description' => ''],
            ['skill' => 'Intuitive Eating', 'description' => ''],
            ['skill' => 'Hydration & Water Therapy', 'description' => ''],
            ['skill' => 'Culinary Wellness & Healthy Cooking', 'description' => ''],
            ['skill' => 'Other', 'description' => ''],
        ];

        DB::table('skills')->insert($skills);
    }
}
