<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ToolSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tools = [ 
            ['tool' => '.NET core', 'image' => '.NET-core.svg'],
            ['tool' => '.NET', 'image' => '.NET.svg'],
            ['tool' => 'AArch64', 'image' => 'AArch64.svg'],
            ['tool' => 'Adobe Commerce (Magneto)', 'image' => 'Adobe-Commerce-(Magneto).svg'],
            ['tool' => 'Adobe Illustrator', 'image' => 'Adobe-Illustrator.svg'],
            ['tool' => 'Adobe Photoshop', 'image' => 'Adobe-Photoshop.svg'],
            ['tool' => 'Adobe Premiere Pro', 'image' => 'Adobe-Premiere-Pro.svg'],
            ['tool' => 'Adobe XD', 'image' => 'Adobe-XD.svg'],
            ['tool' => 'Adobe InDesign', 'image' => ''],
            ['tool' => 'Adobe Lightroom', 'image' => ''],
            ['tool' => 'Adobe Camera Raw', 'image' => ''],
            ['tool' => 'Adobe Premiere Rush', 'image' => ''],
            ['tool' => 'Adobe Animate', 'image' => ''],
            ['tool' => 'Adobe Character Animator', 'image' => ''],
            ['tool' => 'Adobe Dimension', 'image' => ''],
            ['tool' => 'Adobe Dreamweaver', 'image' => ''],
            ['tool' => 'Adobe Spark', 'image' => ''],
            ['tool' => 'Adobe InCopy', 'image' => ''],
            ['tool' => 'Adobe Audition', 'image' => ''],
            ['tool' => 'Adobe Campaign', 'image' => ''],
            ['tool' => 'Adobe Experience Manager', 'image' => ''],
            ['tool' => 'Adobe Stock', 'image' => ''],
            ['tool' => 'Adobe Acrobat Pro', 'image' => ''],
            ['tool' => 'Adobe Sign', 'image' => ''],
            ['tool' => 'Adobe Fresco', 'image' => ''],
            ['tool' => 'AdonisJS', 'image' => 'AdonisJS.svg'],
            ['tool' => 'After Effects', 'image' => 'After-Effects.svg'],
            ['tool' => 'Akka', 'image' => 'Akka.svg'],
            ['tool' => 'Algolia', 'image' => 'Algolia.svg'],
            ['tool' => 'Alpine.js', 'image' => 'Alpine.js.svg'],
            ['tool' => 'Anaconda', 'image' => 'Anaconda.svg'],
            ['tool' => 'Android Studio', 'image' => 'Android-Studio.svg'],
            ['tool' => 'Android', 'image' => 'Android.svg'],
            ['tool' => 'Angular', 'image' => 'Angular.svg'],
            ['tool' => 'AngularJS', 'image' => 'AngularJS.svg'],
            ['tool' => 'Ansible', 'image' => 'Ansible.svg'],
            ['tool' => 'Ant Design', 'image' => 'Ant-Design.svg'],
            ['tool' => 'Apache Airflow', 'image' => 'Apache-Airflow.svg'],
            ['tool' => 'Apache Cassandra', 'image' => 'Apache-Cassandra.svg'],
            ['tool' => 'Apache Groovy', 'image' => 'Apache-Groovy.svg'],
            ['tool' => 'Apache Hadoop', 'image' => 'Apache-Hadoop.svg'],
            ['tool' => 'Apache Kafka', 'image' => 'Apache-Kafka.svg'],
            ['tool' => 'Apache Maven', 'image' => 'Apache-Maven.svg'],
            ['tool' => 'Apache Spark', 'image' => 'Apache-Spark.svg'],
            ['tool' => 'Apache Subversion', 'image' => 'Apache-Subversion.svg'],
            ['tool' => 'Apache Tomcat', 'image' => 'Apache-Tomcat.svg'],
            ['tool' => 'Apache', 'image' => 'Apache.svg'],
            ['tool' => 'APL', 'image' => 'APL.svg'],
            ['tool' => 'Appcelerator', 'image' => 'Appcelerator.svg'],
            ['tool' => 'Apple Safari', 'image' => 'Apple-Safari.svg'],
            ['tool' => 'Apple', 'image' => 'Apple.svg'],
            ['tool' => 'Appwrite', 'image' => 'Appwrite.svg'],
            ['tool' => 'Arch Linux', 'image' => 'Arch-Linux.svg'],
            ['tool' => 'Arduino', 'image' => 'Arduino.svg'],
            ['tool' => 'Argo CD', 'image' => 'Argo-CD.svg'],
            ['tool' => 'Astro', 'image' => 'Astro.svg'],
            ['tool' => 'Atom', 'image' => 'Atom.svg'],
            ['tool' => 'Autodesk Maya', 'image' => 'Autodesk-Maya.svg'],
            ['tool' => 'Autodesk ShotGrid', 'image' => 'Autodesk-ShotGrid.svg'],
            ['tool' => 'Awk', 'image' => 'Awk.svg'],
            ['tool' => 'AWS', 'image' => 'AWS.svg'],
            ['tool' => 'Azios', 'image' => 'Azios.svg'],
            ['tool' => 'Azure Devops', 'image' => 'Azure-Devops.svg'],
            ['tool' => 'Azure SQL Database', 'image' => 'Azure-SQL-Database.svg'],
            ['tool' => 'Azure', 'image' => 'Azure.svg'],
            ['tool' => 'Babel', 'image' => 'Babel.svg'],
            ['tool' => 'Backbone.js', 'image' => 'Backbone.js.svg'],
            ['tool' => 'Ballerina', 'image' => 'Ballerina.svg'],
            ['tool' => 'Bamboo', 'image' => 'Bamboo.svg'],
            ['tool' => 'Bash', 'image' => 'Bash.svg'],
            ['tool' => 'Behance', 'image' => 'Behance.svg'],
            ['tool' => 'BitBucket', 'image' => 'BitBucket.svg'],
            ['tool' => 'Blender', 'image' => 'Blender.svg'],
            ['tool' => 'Bootstrap', 'image' => 'Bootstrap.svg'],
            ['tool' => 'Bower', 'image' => 'Bower.svg'],
            ['tool' => 'BrowserStack', 'image' => 'BrowserStack.svg'],
            ['tool' => 'Bulma', 'image' => 'Bulma.svg'],
            ['tool' => 'Bun', 'image' => 'Bun.svg'],
            ['tool' => 'Busy', 'image' => ''],
            ['tool' => 'Tally ERP 9', 'image' => ''],
            ['tool' => 'Tally', 'image' => ''],
            ['tool' => 'C# (CSharp)', 'image' => 'C#-(CSharp).svg'],
            ['tool' => 'C++ (CPlusPlus)', 'image' => 'C++-(CPlusPlus).svg'],
            ['tool' => 'C', 'image' => 'C.svg'],
            ['tool' => 'Cairo Graphics', 'image' => 'Cairo-Graphics.svg'],
            ['tool' => 'CakePHP', 'image' => 'CakePHP.svg'],
            ['tool' => 'Canva', 'image' => 'Canva.svg'],
            ['tool' => 'Capacitor', 'image' => 'Capacitor.svg'],
            ['tool' => 'CentOS', 'image' => 'CentOS.svg'],
            ['tool' => 'Chrome', 'image' => 'Chrome.svg'],
            ['tool' => 'CircleCI', 'image' => 'CircleCI.svg'],
            ['tool' => 'Clarity', 'image' => 'Clarity.svg'],
            ['tool' => 'CLion', 'image' => 'CLion.svg'],
            ['tool' => 'Clojure', 'image' => 'Clojure.svg'],
            ['tool' => 'ClojureScript', 'image' => 'ClojureScript.svg'],
            ['tool' => 'Cloudflare Workers', 'image' => 'Cloudflare-Workers.svg'],
            ['tool' => 'Cloudflare', 'image' => 'Cloudflare.svg'],
            ['tool' => 'CMake', 'image' => 'CMake.svg'],
            ['tool' => 'Codeac', 'image' => 'Codeac.svg'],
            ['tool' => 'Codecov', 'image' => 'Codecov.svg'],
            ['tool' => 'CodeIgniter', 'image' => 'CodeIgniter.svg'],
            ['tool' => 'CodePen', 'image' => 'CodePen.svg'],
            ['tool' => 'CoffeeScript', 'image' => 'CoffeeScript.svg'],
            ['tool' => 'Composer', 'image' => 'Composer.svg'],
            ['tool' => 'Confluence', 'image' => 'Confluence.svg'],
            ['tool' => 'Consul', 'image' => 'Consul.svg'],
            ['tool' => 'Contao', 'image' => 'Contao.svg'],
            ['tool' => 'Core js', 'image' => 'Core-js.svg'],
            ['tool' => 'Cosmos BD', 'image' => 'Cosmos-BD.svg'],
            ['tool' => 'CouchDB', 'image' => 'CouchDB.svg'],
            ['tool' => 'Crystal', 'image' => 'Crystal.svg'],
            ['tool' => 'CSS3', 'image' => 'CSS3.svg'],
            ['tool' => 'Cucumber', 'image' => 'Cucumber.svg'],
            ['tool' => 'Cypress', 'image' => 'Cypress.svg'],
            ['tool' => 'CorelDRAW', 'image' => ''],
            ['tool' => 'D3.js', 'image' => 'D3.js.svg'],
            ['tool' => 'Dart', 'image' => 'Dart.svg'],
            ['tool' => 'DataGrip', 'image' => 'DataGrip.svg'],
            ['tool' => 'DataSpell', 'image' => 'DataSpell.svg'],
            ['tool' => 'DBeaver', 'image' => 'DBeaver.svg'],
            ['tool' => 'Debian', 'image' => 'Debian.svg'],
            ['tool' => 'Deno', 'image' => 'Deno.svg'],
            ['tool' => 'Devicon', 'image' => 'Devicon.svg'],
            ['tool' => 'Digital Ocean', 'image' => 'Digital-Ocean.svg'],
            ['tool' => 'Discord.js', 'image' => 'Discord.js.svg'],
            ['tool' => 'Django REST', 'image' => 'Django-REST.svg'],
            ['tool' => 'Django', 'image' => 'Django.svg'],
            ['tool' => 'Docker', 'image' => 'Docker.svg'],
            ['tool' => 'Doctrine', 'image' => 'Doctrine.svg'],
            ['tool' => 'Dropwizard', 'image' => 'Dropwizard.svg'],
            ['tool' => 'Drupal', 'image' => 'Drupal.svg'],
            ['tool' => 'Eclipse Ceylon', 'image' => 'Eclipse-Ceylon.svg'],
            ['tool' => 'Eclipse IDE', 'image' => 'Eclipse-IDE.svg'],
            ['tool' => 'Eclipse Vert.x', 'image' => 'Eclipse-Vert.x.svg'],
            ['tool' => 'Elastic Beats', 'image' => 'Elastic-Beats.svg'],
            ['tool' => 'Elastic Search', 'image' => 'Elastic-Search.svg'],
            ['tool' => 'Electron', 'image' => 'Electron.svg'],
            ['tool' => 'Eleventy (11ty)', 'image' => 'Eleventy-(11ty).svg'],
            ['tool' => 'Elixir', 'image' => 'Elixir.svg'],
            ['tool' => 'Elm', 'image' => 'Elm.svg'],
            ['tool' => 'Embedded C', 'image' => 'Embedded-C.svg'],
            ['tool' => 'Ember.js', 'image' => 'Ember.js.svg'],
            ['tool' => 'Envoy', 'image' => 'Envoy.svg'],
            ['tool' => 'Erlang', 'image' => 'Erlang.svg'],
            ['tool' => 'ESLint', 'image' => 'ESLint.svg'],
            ['tool' => 'Express', 'image' => 'Express.svg'],
            ['tool' => 'Excel', 'image' => ''],
            ['tool' => 'Facebook', 'image' => 'Facebook.svg'],
            ['tool' => 'FastAPI', 'image' => 'FastAPI.svg'],
            ['tool' => 'Fastify', 'image' => 'Fastify.svg'],
            ['tool' => 'Fauna', 'image' => 'Fauna.svg'],
            ['tool' => 'Feathers', 'image' => 'Feathers.svg'],
            ['tool' => 'Fedora', 'image' => 'Fedora.svg'],
            ['tool' => 'Figma', 'image' => 'Figma.svg'],
            ['tool' => 'FileZilla', 'image' => 'FileZilla.svg'],
            ['tool' => 'Firebase', 'image' => 'Firebase.svg'],
            ['tool' => 'Firefox', 'image' => 'Firefox.svg'],
            ['tool' => 'Flask', 'image' => 'Flask.svg'],
            ['tool' => 'Flutter', 'image' => 'Flutter.svg'],
            ['tool' => 'Fortran', 'image' => 'Fortran.svg'],
            ['tool' => 'Foundation', 'image' => 'Foundation.svg'],
            ['tool' => 'FSharp (F#)', 'image' => 'FSharp-(F#).svg'],
            ['tool' => 'Gatling', 'image' => 'Gatling.svg'],
            ['tool' => 'Gatsby', 'image' => 'Gatsby.svg'],
            ['tool' => 'Gazebo', 'image' => 'Gazebo.svg'],
            ['tool' => 'GCC', 'image' => 'GCC.svg'],
            ['tool' => 'Gentoo', 'image' => 'Gentoo.svg'],
            ['tool' => 'Ghost', 'image' => 'Ghost.svg'],
            ['tool' => 'GIMP', 'image' => 'GIMP.svg'],
            ['tool' => 'Git', 'image' => 'Git.svg'],
            ['tool' => 'GitBook', 'image' => 'GitBook.svg'],
            ['tool' => 'GitHub Actions', 'image' => 'GitHub-Actions.svg'],
            ['tool' => 'GitHub Codespaces', 'image' => 'GitHub-Codespaces.svg'],
            ['tool' => 'GitHub', 'image' => 'GitHub.svg'],
            ['tool' => 'GitLab', 'image' => 'GitLab.svg'],
            ['tool' => 'Gitpod', 'image' => 'Gitpod.svg'],
            ['tool' => 'Gitter', 'image' => 'Gitter.svg'],
            ['tool' => 'GNU Emacs', 'image' => 'GNU-Emacs.svg'],
            ['tool' => 'Go', 'image' => 'Go.svg'],
            ['tool' => 'Godot Engine', 'image' => 'Godot-Engine.svg'],
            ['tool' => 'GoLand', 'image' => 'GoLand.svg'],
            ['tool' => 'Google Cloud', 'image' => 'Google-Cloud.svg'],
            ['tool' => 'Google', 'image' => 'Google.svg'],
            ['tool' => 'Gradle', 'image' => 'Gradle.svg'],
            ['tool' => 'Grafana', 'image' => 'Grafana.svg'],
            ['tool' => 'Grails', 'image' => 'Grails.svg'],
            ['tool' => 'GraphQL', 'image' => 'GraphQL.svg'],
            ['tool' => 'Grunt.js', 'image' => 'Grunt.js.svg'],
            ['tool' => 'Gulp.js', 'image' => 'Gulp.js.svg'],
            ['tool' => 'Handlebars', 'image' => 'Handlebars.svg'],
            ['tool' => 'Hardhat', 'image' => 'Hardhat.svg'],
            ['tool' => 'Harvester', 'image' => 'Harvester.svg'],
            ['tool' => 'HashiCorp Terraform', 'image' => 'HashiCorp-Terraform.svg'],
            ['tool' => 'HashiCorp Vagrant', 'image' => 'HashiCorp-Vagrant.svg'],
            ['tool' => 'HashiCorp Vault', 'image' => 'HashiCorp-Vault.svg'],
            ['tool' => 'Haskell', 'image' => 'Haskell.svg'],
            ['tool' => 'Haxe', 'image' => 'Haxe.svg'],
            ['tool' => 'Helm', 'image' => 'Helm.svg'],
            ['tool' => 'Heroku', 'image' => 'Heroku.svg'],
            ['tool' => 'Hibernate', 'image' => 'Hibernate.svg'],
            ['tool' => 'Homebrew', 'image' => 'Homebrew.svg'],
            ['tool' => 'HTML5', 'image' => 'HTML5.svg'],
            ['tool' => 'Hugo', 'image' => 'Hugo.svg'],
            ['tool' => 'HubSpot', 'image' => ''],
            ['tool' => 'IBM SPSS Statistics', 'image' => 'IBM-SPSS-Statistics.svg'],
            ['tool' => 'IFTTT', 'image' => 'IFTTT.svg'],
            ['tool' => 'InfluxDB', 'image' => 'InfluxDB.svg'],
            ['tool' => 'Inkscape ', 'image' => 'Inkscape-.svg'],
            ['tool' => 'Insomnia', 'image' => 'Insomnia.svg'],
            ['tool' => 'IntelliJ IDEA', 'image' => 'IntelliJ-IDEA.svg'],
            ['tool' => 'Internet Explorer 10 (ie10)', 'image' => 'Internet-Explorer-10-(ie10).svg'],
            ['tool' => 'Ionic', 'image' => 'Ionic.svg'],
            ['tool' => 'Jaeger Tracing', 'image' => 'Jaeger-Tracing.svg'],
            ['tool' => 'Jamstack', 'image' => 'Jamstack.svg'],
            ['tool' => 'Jasmine', 'image' => 'Jasmine.svg'],
            ['tool' => 'Java', 'image' => 'Java.svg'],
            ['tool' => 'JavaScript', 'image' => 'JavaScript.svg'],
            ['tool' => 'Jeet', 'image' => 'Jeet.svg'],
            ['tool' => 'Jekyll', 'image' => 'Jekyll.svg'],
            ['tool' => 'Jenkins', 'image' => 'Jenkins.svg'],
            ['tool' => 'Jest', 'image' => 'Jest.svg'],
            ['tool' => 'JetBrains', 'image' => 'JetBrains.svg'],
            ['tool' => 'Jira Align', 'image' => 'Jira-Align.svg'],
            ['tool' => 'Jira', 'image' => 'Jira.svg'],
            ['tool' => 'jQuery', 'image' => 'jQuery.svg'],
            ['tool' => 'JSON', 'image' => 'JSON.svg'],
            ['tool' => 'Jule', 'image' => 'Jule.svg'],
            ['tool' => 'Julia', 'image' => 'Julia.svg'],
            ['tool' => 'JUnit', 'image' => 'JUnit.svg'],
            ['tool' => 'Jupyter', 'image' => 'Jupyter.svg'],
            ['tool' => 'K3OS', 'image' => 'K3OS.svg'],
            ['tool' => 'K3s', 'image' => 'K3s.svg'],
            ['tool' => 'Kaggle', 'image' => 'Kaggle.svg'],
            ['tool' => 'Karate Labs', 'image' => 'Karate-Labs.svg'],
            ['tool' => 'Karma', 'image' => 'Karma.svg'],
            ['tool' => 'Keras', 'image' => 'Keras.svg'],
            ['tool' => 'Kibana', 'image' => 'Kibana.svg'],
            ['tool' => 'Knex.js', 'image' => 'Knex.js.svg'],
            ['tool' => 'Knockout', 'image' => 'Knockout.svg'],
            ['tool' => 'Kotlin', 'image' => 'Kotlin.svg'],
            ['tool' => 'Krakenjs', 'image' => 'Krakenjs.svg'],
            ['tool' => 'Ktor', 'image' => 'Ktor.svg'],
            ['tool' => 'Kubernetes', 'image' => 'Kubernetes.svg'],
            ['tool' => 'LabVIEW', 'image' => 'LabVIEW.svg'],
            ['tool' => 'Laravel', 'image' => 'Laravel.svg'],
            ['tool' => 'LaTeX', 'image' => 'LaTeX.svg'],
            ['tool' => 'Less.js', 'image' => 'Less.js.svg'],
            ['tool' => 'LinkedIn', 'image' => 'LinkedIn.svg'],
            ['tool' => 'Linux', 'image' => 'Linux.svg'],
            ['tool' => 'Liquibase', 'image' => 'Liquibase.svg'],
            ['tool' => 'Livewire', 'image' => 'Livewire.svg'],
            ['tool' => 'LLVM', 'image' => 'LLVM.svg'],
            ['tool' => 'Logstash', 'image' => 'Logstash.svg'],
            ['tool' => 'Lua', 'image' => 'Lua.svg'],
            ['tool' => 'Lumen', 'image' => 'Lumen.svg'],
            ['tool' => 'Markdown', 'image' => 'Markdown.svg'],
            ['tool' => 'Material UI', 'image' => 'Material-UI.svg'],
            ['tool' => 'Materialize', 'image' => 'Materialize.svg'],
            ['tool' => 'MATLAB', 'image' => 'MATLAB.svg'],
            ['tool' => 'Matplotlib', 'image' => 'Matplotlib.svg'],
            ['tool' => 'Meteor.js', 'image' => 'Meteor.js.svg'],
            ['tool' => 'Microsoft SQL Server', 'image' => 'Microsoft-SQL-Server.svg'],
            ['tool' => 'Minitab', 'image' => 'Minitab.svg'],
            ['tool' => 'MobX', 'image' => 'MobX.svg'],
            ['tool' => 'Mocha', 'image' => 'Mocha.svg'],
            ['tool' => 'MODX', 'image' => 'MODX.svg'],
            ['tool' => 'Moleculer', 'image' => 'Moleculer.svg'],
            ['tool' => 'MongoDB', 'image' => 'MongoDB.svg'],
            ['tool' => 'Mongoose.js', 'image' => 'Mongoose.js.svg'],
            ['tool' => 'Moodle', 'image' => 'Moodle.svg'],
            ['tool' => 'MS DOS', 'image' => 'MS-DOS.svg'],
            ['tool' => 'MySQL', 'image' => 'MySQL.svg'],
            ['tool' => 'Microsoft Excel', 'image' => ''],
            ['tool' => 'Microsoft Word', 'image' => ''],
            ['tool' => 'Microsoft PowerPoint', 'image' => ''],
            ['tool' => 'Microsoft Outlook', 'image' => ''],
            ['tool' => 'Nano', 'image' => 'Nano.svg'],
            ['tool' => 'Nerog', 'image' => 'Nerog.svg'],
            ['tool' => 'Nest.js', 'image' => 'Nest.js.svg'],
            ['tool' => 'NetworkX', 'image' => 'NetworkX.svg'],
            ['tool' => 'New4j', 'image' => 'New4j.svg'],
            ['tool' => 'Next.js', 'image' => 'Next.js.svg'],
            ['tool' => 'NGINX', 'image' => 'NGINX.svg'],
            ['tool' => 'NHibernate', 'image' => 'NHibernate.svg'],
            ['tool' => 'Nim', 'image' => 'Nim.svg'],
            ['tool' => 'Nimble', 'image' => 'Nimble.svg'],
            ['tool' => 'NixOS', 'image' => 'NixOS.svg'],
            ['tool' => 'Node.js', 'image' => 'Node.js.svg'],
            ['tool' => 'Nodemon', 'image' => 'Nodemon.svg'],
            ['tool' => 'NPM', 'image' => 'NPM.svg'],
            ['tool' => 'NuGet', 'image' => 'NuGet.svg'],
            ['tool' => 'NumPy', 'image' => 'NumPy.svg'],
            ['tool' => 'Nuxt JS', 'image' => 'Nuxt-JS.svg'],
            ['tool' => 'NW.js (node webkit)', 'image' => 'NW.js-(node-webkit).svg'],
            ['tool' => 'Objective C', 'image' => 'Objective-C.svg'],
            ['tool' => 'OCaml', 'image' => 'OCaml.svg'],
            ['tool' => 'Oh my zsh', 'image' => 'Oh-my-zsh.svg'],
            ['tool' => 'Okta', 'image' => 'Okta.svg'],
            ['tool' => 'OpenAL', 'image' => 'OpenAL.svg'],
            ['tool' => 'OpenAPI', 'image' => 'OpenAPI.svg'],
            ['tool' => 'OpenCL', 'image' => 'OpenCL.svg'],
            ['tool' => 'OpenCV', 'image' => 'OpenCV.svg'],
            ['tool' => 'OpenGL', 'image' => 'OpenGL.svg'],
            ['tool' => 'OpenStack', 'image' => 'OpenStack.svg'],
            ['tool' => 'openSUSE', 'image' => 'openSUSE.svg'],
            ['tool' => 'OpenTelemetry', 'image' => 'OpenTelemetry.svg'],
            ['tool' => 'Opera', 'image' => 'Opera.svg'],
            ['tool' => 'Oracle', 'image' => 'Oracle.svg'],
            ['tool' => 'OneDrive', 'image' => ''],
            ['tool' => 'p5 JS', 'image' => 'p5-JS.svg'],
            ['tool' => 'Packer', 'image' => 'Packer.svg'],
            ['tool' => 'Pandas', 'image' => 'Pandas.svg'],
            ['tool' => 'Perl', 'image' => 'Perl.svg'],
            ['tool' => 'pfSense', 'image' => 'pfSense.svg'],
            ['tool' => 'Phalcon', 'image' => 'Phalcon.svg'],
            ['tool' => 'Phoenix Framework', 'image' => 'Phoenix-Framework.svg'],
            ['tool' => 'Photon Engine ', 'image' => 'Photon-Engine-.svg'],
            ['tool' => 'PHP', 'image' => 'PHP.svg'],
            ['tool' => 'PhpStorm', 'image' => 'PhpStorm.svg'],
            ['tool' => 'Playwrite', 'image' => 'Playwrite.svg'],
            ['tool' => 'Ploty', 'image' => 'Ploty.svg'],
            ['tool' => 'Podman', 'image' => 'Podman.svg'],
            ['tool' => 'Polygon', 'image' => 'Polygon.svg'],
            ['tool' => 'Portainer', 'image' => 'Portainer.svg'],
            ['tool' => 'PostCSS', 'image' => 'PostCSS.svg'],
            ['tool' => 'PostgresSQL', 'image' => 'PostgresSQL.svg'],
            ['tool' => 'Postman', 'image' => 'Postman.svg'],
            ['tool' => 'Powershell', 'image' => 'Powershell.svg'],
            ['tool' => 'Processing', 'image' => 'Processing.svg'],
            ['tool' => 'Prometheus', 'image' => 'Prometheus.svg'],
            ['tool' => 'Protractor Test', 'image' => 'Protractor-Test.svg'],
            ['tool' => 'PureScript', 'image' => 'PureScript.svg'],
            ['tool' => 'PuTTY', 'image' => 'PuTTY.svg'],
            ['tool' => 'PyCharm', 'image' => 'PyCharm.svg'],
            ['tool' => 'PyScript', 'image' => 'PyScript.svg'],
            ['tool' => 'pytest', 'image' => 'pytest.svg'],
            ['tool' => 'Python Poetry', 'image' => 'Python-Poetry.svg'],
            ['tool' => 'Python', 'image' => 'Python.svg'],
            ['tool' => 'PyTorch', 'image' => 'PyTorch.svg'],
            ['tool' => 'Power BI', 'image' => 'PyTorch.svg'],
            ['tool' => 'Qodana', 'image' => 'Qodana.svg'],
            ['tool' => 'Qt Framework', 'image' => 'Qt-Framework.svg'],
            ['tool' => 'Quarkus', 'image' => 'Quarkus.svg'],
            ['tool' => 'Quasar', 'image' => 'Quasar.svg'],
            ['tool' => 'Qwik', 'image' => 'Qwik.svg'],
            ['tool' => 'R ', 'image' => 'R-.svg'],
            ['tool' => 'RabbitMQ', 'image' => 'RabbitMQ.svg'],
            ['tool' => 'Rancher', 'image' => 'Rancher.svg'],
            ['tool' => 'Raspberry Pi', 'image' => 'Raspberry-Pi.svg'],
            ['tool' => 'Reach', 'image' => 'Reach.svg'],
            ['tool' => 'React Bootstrap', 'image' => 'React-Bootstrap.svg'],
            ['tool' => 'React', 'image' => 'React.svg'],
            ['tool' => 'Realm', 'image' => 'Realm.svg'],
            ['tool' => 'Red Hat', 'image' => 'Red-Hat.svg'],
            ['tool' => 'RedCube epic Compiler Thingy programming (ReCT)', 'image' => 'RedCubes-epic-Compiler-Thingy-programming-(ReCT).svg'],
            ['tool' => 'Redis', 'image' => 'Redis.svg'],
            ['tool' => 'Redux', 'image' => 'Redux.svg'],
            ['tool' => 'Ren Py', 'image' => 'RenPy.svg'],
            ['tool' => 'Rider', 'image' => 'Rider.svg'],
            ['tool' => 'Robot Operating System (ROS)', 'image' => 'Robot-Operating-System-(ROS).svg'],
            ['tool' => 'RocksDB', 'image' => 'RocksDB.svg'],
            ['tool' => 'Rollup.js', 'image' => 'Rollup.js.svg'],
            ['tool' => 'RSpec', 'image' => 'RSpec.svg'],
            ['tool' => 'RStudio', 'image' => 'RStudio.svg'],
            ['tool' => 'Ruby on Rails', 'image' => 'Ruby-on-Rails.svg'],
            ['tool' => 'Ruby', 'image' => 'Ruby.svg'],
            ['tool' => 'RubyMine', 'image' => 'RubyMine.svg'],
            ['tool' => 'Rust', 'image' => 'Rust.svg'],
            ['tool' => 'Salesforce', 'image' => 'Salesforce.svg'],
            ['tool' => 'Sanity', 'image' => 'Sanity.svg'],
            ['tool' => 'Sass', 'image' => 'Sass.svg'],
            ['tool' => 'Scala', 'image' => 'Scala.svg'],
            ['tool' => 'Scalingo', 'image' => 'Scalingo.svg'],
            ['tool' => 'Selenium', 'image' => 'Selenium.svg'],
            ['tool' => 'Sema Software', 'image' => 'Sema-Software.svg'],
            ['tool' => 'Sequelize', 'image' => 'Sequelize.svg'],
            ['tool' => 'Shopware', 'image' => 'Shopware.svg'],
            ['tool' => 'Simple DirectMedia Layer (SDL)', 'image' => 'Simple-DirectMedia-Layer-(SDL).svg'],
            ['tool' => 'Sketch', 'image' => 'Sketch.svg'],
            ['tool' => 'Slack', 'image' => 'Slack.svg'],
            ['tool' => 'Socket.io', 'image' => 'Socket.io.svg'],
            ['tool' => 'Solid.js', 'image' => 'Solid.js.svg'],
            ['tool' => 'Solidity', 'image' => 'Solidity.svg'],
            ['tool' => 'SonarQube', 'image' => 'SonarQube.svg'],
            ['tool' => 'Sourcetree', 'image' => 'Sourcetree.svg'],
            ['tool' => 'Splunk', 'image' => 'Splunk.svg'],
            ['tool' => 'Spring', 'image' => 'Spring.svg'],
            ['tool' => 'SQL Developer', 'image' => 'SQL-Developer.svg'],
            ['tool' => 'SQLAlchemy', 'image' => 'SQLAlchemy.svg'],
            ['tool' => 'SQLite', 'image' => 'SQLite.svg'],
            ['tool' => 'SSH', 'image' => 'SSH.svg'],
            ['tool' => 'Stack Overflow', 'image' => 'Stack-Overflow.svg'],
            ['tool' => 'Stata', 'image' => 'Stata.svg'],
            ['tool' => 'Storybook', 'image' => 'Storybook.svg'],
            ['tool' => 'Streamlit', 'image' => 'Streamlit.svg'],
            ['tool' => 'Stylus', 'image' => 'Stylus.svg'],
            ['tool' => 'Svelte', 'image' => 'Svelte.svg'],
            ['tool' => 'Swagger', 'image' => 'Swagger.svg'],
            ['tool' => 'Swift', 'image' => 'Swift.svg'],
            ['tool' => 'Symfony', 'image' => 'Symfony.svg'],
            ['tool' => 'SEMrush', 'image' => ''],
            ['tool' => 'SolidWorks', 'image' => ''],
            ['tool' => 'SAP ERP', 'image' => ''],
            ['tool' => 'CATIA', 'image' => ''],
            ['tool' => 'Siemens NX', 'image' => ''],
            ['tool' => 'PTC Creo', 'image' => ''],
            ['tool' => 'Rhino', 'image' => ''],
            ['tool' => 'Inventor', 'image' => ''],
            ['tool' => 'Fusion 360', 'image' => ''],
            ['tool' => 'Tailwind CSS', 'image' => 'Tailwind-CSS.svg'],
            ['tool' => 'Tauri', 'image' => 'Tauri.svg'],
            ['tool' => 'TensorFlow', 'image' => 'TensorFlow.svg'],
            ['tool' => 'TeX', 'image' => 'TeX.svg'],
            ['tool' => 'The Algorithms', 'image' => 'The-Algorithms.svg'],
            ['tool' => 'Three.js', 'image' => 'Three.js.svg'],
            ['tool' => 'Titanium SDK', 'image' => 'Titanium-SDK.svg'],
            ['tool' => 'TortoiseGit', 'image' => 'TortoiseGit.svg'],
            ['tool' => 'Tower', 'image' => 'Tower.svg'],
            ['tool' => 'Traefik Mesh', 'image' => 'Traefik-Mesh.svg'],
            ['tool' => 'Traefik Proxy', 'image' => 'Traefik-Proxy.svg'],
            ['tool' => 'Travis CI', 'image' => 'Travis-CI.svg'],
            ['tool' => 'Trello', 'image' => 'Trello.svg'],
            ['tool' => 'Twitter', 'image' => 'Twitter.svg'],
            ['tool' => 'TypeScript', 'image' => 'TypeScript.svg'],
            ['tool' => 'TYPO3', 'image' => 'TYPO3.svg'],
            ['tool' => 'Tableau', 'image' => ''],
            ['tool' => 'TurboTax', 'image' => ''],
            ['tool' => 'H&R Block', 'image' => ''],
            ['tool' => 'TaxAct', 'image' => ''],
            ['tool' => 'Ubuntu', 'image' => 'Ubuntu.svg'],
            ['tool' => 'Unified Modelling Language (UML)', 'image' => 'Unified-Modelling-Language-(UML).svg'],
            ['tool' => 'Unity', 'image' => 'Unity.svg'],
            ['tool' => 'UNIX', 'image' => 'UNIX.svg'],
            ['tool' => 'Unreal Engine', 'image' => 'Unreal-Engine.svg'],
            ['tool' => 'uWSGI', 'image' => 'uWSGI.svg'],
            ['tool' => 'V8', 'image' => 'V8.svg'],
            ['tool' => 'Vala', 'image' => 'Vala.svg'],
            ['tool' => 'Vercel', 'image' => 'Vercel.svg'],
            ['tool' => 'Veutify', 'image' => 'Veutify.svg'],
            ['tool' => 'Vim', 'image' => 'Vim.svg'],
            ['tool' => 'Visual Studio Code (VS Code)', 'image' => 'Visual-Studio-Code-(VS-Code).svg'],
            ['tool' => 'Visual Studio', 'image' => 'Visual-Studio.svg'],
            ['tool' => 'Vite.js', 'image' => 'Vite.js.svg'],
            ['tool' => 'Vite', 'image' => 'Vite.svg'],
            ['tool' => 'vSphere', 'image' => 'vSphere.svg'],
            ['tool' => 'Vue Storefront', 'image' => 'Vue-Storefront.svg'],
            ['tool' => 'Vue.js', 'image' => 'Vue.js.svg'],
            ['tool' => 'Vyper', 'image' => 'Vyper.svg'],
            ['tool' => 'WebAssembly', 'image' => 'WebAssembly.svg'],
            ['tool' => 'Webflow', 'image' => 'Webflow.svg'],
            ['tool' => 'Weblate', 'image' => 'Weblate.svg'],
            ['tool' => 'Webpack', 'image' => 'Webpack.svg'],
            ['tool' => 'WebStorm', 'image' => 'WebStorm.svg'],
            ['tool' => 'Windows 11', 'image' => 'Windows-11.svg'],
            ['tool' => 'Windows 8', 'image' => 'Windows-8.svg'],
            ['tool' => 'WooCommerce', 'image' => 'WooCommerce.svg'],
            ['tool' => 'WordPress', 'image' => 'WordPress.svg'],
            ['tool' => 'Wireshark', 'image' => ''],
            ['tool' => 'SolarWinds', 'image' => ''],
            ['tool' => 'Nagios', 'image' => ''],
            ['tool' => 'Xamarin', 'image' => 'Xamarin.svg'],
            ['tool' => 'Xcode', 'image' => 'Xcode.svg'],
            ['tool' => 'XML', 'image' => 'XML.svg'],
            ['tool' => 'YAML', 'image' => 'YAML.svg'],
            ['tool' => 'Yarn', 'image' => 'Yarn.svg'],
            ['tool' => 'Yii Framework', 'image' => 'Yii-Framework.svg'],
            ['tool' => 'Yuno Host', 'image' => 'Yuno-Host.svg'],
            ['tool' => 'Zend Framework', 'image' => 'Zend-Framework.svg'],
            ['tool' => 'Zig', 'image' => 'Zig.svg'],
            ['tool' => 'Other', 'image' => ''],
        ]; 

        DB::table('tools')->insert($tools);


    }
}
